# fly.toml app configuration file generated for redis-mcp on 2025-07-25T02:37:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'redis-mcp'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
